[package]
name = "zifu"
version = "0.1.0"
authors = ["Tatsunori Uchino <tats.u@live.jp>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/tats-u/zifu/"
description = "Repair corrupted file names in ZIP archives"
categories = ["command-line-utilities"]
keywords = ["zip", "archive", "utf-8", "encoding"]

[[bin]]
name = "zifu"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
clap = "3.0.0-beta.1"
byteorder = "1.3.4"
anyhow = "1.0.32"
thiserror = "1.0.20"
encoding_rs = "0.8.23"
bytesize = "1.0.1"
locale_config = "0.3.0"