[package]
name = "zip-filename-utf8"
version = "0.1.0"
authors = ["Tatsunori Uchino <tats.u@live.jp>"]
edition = "2018"

[[bin]]
name = "zfu"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
clap = "3.0.0-beta.1"
byteorder = "1.3.4"
anyhow = "1.0.31"
thiserror = "1.0.20"
encoding_rs = "0.8.23"
bytesize = "1.0.1"
locale_config = "0.3.0"